### ISSUE TITLE
Add render <App/> test

### ISSUE THREAD

**Issue by GabCh** [GabCh/nodes-website#5]
`ReactDOM` throws exception when rendering the `<App />` component. I use enzyme as temporary solution but `shallow` does not do the job apparently.

**Comment by Gab05** [comment]
`mount` from enzyme instead of `shallow` might do the trick

**Comment by Gab05** [comment]
Using ReactDOM for tests purposes does not seem necessary. `enzyme`'s `ShallowWrapper` successfully renders the App and its components
